services:
  app:
    image: hr-management-devcontainer:latest
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - redis
      - mysql

    environment:
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379

      # MySQL
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: appdb

    networks:
      - devnet

  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - devnet

  mysql:
    image: mysql:8.3
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb

    volumes:
      - mysql-data:/var/lib/mysql

    networks:
      - devnet

volumes:
  redis-data:
  mysql-data:

networks:
  devnet:
    driver: bridge
